# -*- coding: utf-8 -*-
"""Named_Entity_Recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N0AFILxOGMDpq1TX3yNqkDQ-0QfGD_sG

# Using Spacy Package for Named Entity Recognition
"""

import numpy as np
import nltk, re
from nltk.util import ngrams
import spacy
from spacy.lang.en import English
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import sent_tokenize


def get_highlighted_list(text):
    nlp = spacy.load('en_core_web_sm')
    text = nlp(text)
    filter_list = ["GPE", "ORG", "PERSON"]
    bold_list= []
    for entity in text.ents:
        if entity.label_ in filter_list:
            bold_list.append(entity.text)
    return bold_list

def NER_summary(text):
    summary_lst = text.split(" ")
    for i in range(len(summary_lst)):
        if summary_lst[i] in get_highlighted_list(text):
            summary_lst[i] = "<strong>" + summary_lst[i] + "</strong>"
    return " ".join(summary_lst)
