# -*- coding: utf-8 -*-
"""Named_Entity_Recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N0AFILxOGMDpq1TX3yNqkDQ-0QfGD_sG

# Using Spacy Package for Named Entity Recognition
"""

!pip install flask Flask-Markdown spacy

from flask import Flask,url_for,render_template,request
from flaskext.markdown import Markdown
import numpy as np
import nltk, re
import spacy
from spacy.lang.en import English
from nltk.tokenize import sent_tokenize
from spacy import displacy
import json

app = Flask(__name__)
Markdown(app)
HTML_WRAPPER = """<div style="overflow-x: auto; border: 1px solid #e6e9ef; border-radius: 0.25rem; padding: 1rem">{}</div>"""

@app.route('/')
def index():
	return render_template('index.html')


@app.route('/extract',methods=["GET","POST"])
def extract():
  nlp = spacy.load('en_core_web_sm')
  filter = {'ents':['GPE', 'ORG', 'PERSON']}
  if request.method == 'POST':
    raw_text = request.form['rawtext']
    docx = nlp(raw_text) 
    html = displacy.render(docx,style="ent", jupyter=True, options = filter)
    html = html.replace("\n\n","\n")
    result = HTML_WRAPPER.format(html)
  return render_template('result.html',rawtext=raw_text,result=result)


@app.route('/previewer')
def previewer():
	return render_template('previewer.html')

@app.route('/preview',methods=["GET","POST"])
def preview():
	if request.method == 'POST':
		newtext = request.form['newtext']
		result = newtext
	return render_template('preview.html',newtext=newtext,result=result)


if __name__ == '__main__':
  app.run(debug=True)



